# Add Column

In [1]:
import pandas as pd
df = pd.read_csv('../data.csv')

In [2]:
df.head()

,id,date,first_name,last_name,email,gender,ip_address,country,price_paid,tax
0,1,03/28/2021,Marylin,Alders,malders0@shop-pro.jp,Male,160.119.8.119,Canada,$5.36,NaN
1,2,03/19/2021,Hinda,Harridge,hharridge1@gnu.org,Female,210.51.172.132,Canada,$8.32,NaN
2,3,03/17/2021,Erl,Kilminster,ekilminster2@etsy.com,Male,213.8.101.145,United States,$3.73,20.0
3,4,03/19/2021,Grata,Brantl,gbrantl3@umn.edu,Female,5.140.237.101,United States,$3.70,20.0
4,5,03/24/2021,Kanya,Beasant,kbeasant4@jigsy.com,Male,106.252.162.233,Morocco,$9.24,20.0

In [3]:
df = df.fillna(value={'tax': 0})

In [4]:
df

,id,date,first_name,last_name,email,gender,ip_address,country,price_paid,tax
0,1,03/28/2021,Marylin,Alders,malders0@shop-pro.jp,Male,160.119.8.119,Canada,$5.36,0.0
1,2,03/19/2021,Hinda,Harridge,hharridge1@gnu.org,Female,210.51.172.132,Canada,$8.32,0.0
2,3,03/17/2021,Erl,Kilminster,ekilminster2@etsy.com,Male,213.8.101.145,United States,$3.73,20.0
3,4,03/19/2021,Grata,Brantl,gbrantl3@umn.edu,Female,5.140.237.101,United States,$3.70,20.0
4,5,03/24/2021,Kanya,Beasant,kbeasant4@jigsy.com,Male,106.252.162.233,Morocco,$9.24,20.0
...,...,...,...,...,...,...,...,...,...,...
995,996,03/24/2021,Duff,Errigo,derrigorn@elpais.com,Female,193.84.247.144,France,$3.63,0.0
996,997,03/17/2021,Ame,Rastall,arastallro@toplist.cz,Female,188.219.12.109,NaN,$4.59,20.0
997,998,03/13/2021,Betty,Stickels,bstickelsrp@cloudflare.com,Male,199.80.60.87,United States,$7.54,20.0
998,999,03/17/2021,Paquito,Tesoe,ptesoerq@rakuten.co.jp,Male,0.183.63.11,United States,$5.81,0.0
999,1000,03/23/2021,Rochelle,Pringuer,rpringuerrr@house.gov,NaN,170.193.249.83,Canada,$8.01,20.0

In [5]:
df.dtypes

id              int64
date              str
first_name        str
last_name         str
email             str
gender            str
ip_address        str
country           str
price_paid        str
tax           float64
dtype: object

In [6]:
df.price_paid = df.price_paid.apply(lambda x: x.replace('$', ''))
df.price_paid = df.price_paid.astype(float)

In [7]:
df.dtypes

id              int64
date              str
first_name        str
last_name         str
email             str
gender            str
ip_address        str
country           str
price_paid    float64
tax           float64
dtype: object

In [8]:
df

,id,date,first_name,last_name,email,gender,ip_address,country,price_paid,tax
0,1,03/28/2021,Marylin,Alders,malders0@shop-pro.jp,Male,160.119.8.119,Canada,5.36,0.0
1,2,03/19/2021,Hinda,Harridge,hharridge1@gnu.org,Female,210.51.172.132,Canada,8.32,0.0
2,3,03/17/2021,Erl,Kilminster,ekilminster2@etsy.com,Male,213.8.101.145,United States,3.73,20.0
3,4,03/19/2021,Grata,Brantl,gbrantl3@umn.edu,Female,5.140.237.101,United States,3.70,20.0
4,5,03/24/2021,Kanya,Beasant,kbeasant4@jigsy.com,Male,106.252.162.233,Morocco,9.24,20.0
...,...,...,...,...,...,...,...,...,...,...
995,996,03/24/2021,Duff,Errigo,derrigorn@elpais.com,Female,193.84.247.144,France,3.63,0.0
996,997,03/17/2021,Ame,Rastall,arastallro@toplist.cz,Female,188.219.12.109,NaN,4.59,20.0
997,998,03/13/2021,Betty,Stickels,bstickelsrp@cloudflare.com,Male,199.80.60.87,United States,7.54,20.0
998,999,03/17/2021,Paquito,Tesoe,ptesoerq@rakuten.co.jp,Male,0.183.63.11,United States,5.81,0.0
999,1000,03/23/2021,Rochelle,Pringuer,rpringuerrr@house.gov,NaN,170.193.249.83,Canada,8.01,20.0

In [9]:
df['test'] = 0

In [10]:
df

,id,date,first_name,last_name,email,gender,ip_address,country,price_paid,tax,test
0,1,03/28/2021,Marylin,Alders,malders0@shop-pro.jp,Male,160.119.8.119,Canada,5.36,0.0,0
1,2,03/19/2021,Hinda,Harridge,hharridge1@gnu.org,Female,210.51.172.132,Canada,8.32,0.0,0
2,3,03/17/2021,Erl,Kilminster,ekilminster2@etsy.com,Male,213.8.101.145,United States,3.73,20.0,0
3,4,03/19/2021,Grata,Brantl,gbrantl3@umn.edu,Female,5.140.237.101,United States,3.70,20.0,0
4,5,03/24/2021,Kanya,Beasant,kbeasant4@jigsy.com,Male,106.252.162.233,Morocco,9.24,20.0,0
...,...,...,...,...,...,...,...,...,...,...,...
995,996,03/24/2021,Duff,Errigo,derrigorn@elpais.com,Female,193.84.247.144,France,3.63,0.0,0
996,997,03/17/2021,Ame,Rastall,arastallro@toplist.cz,Female,188.219.12.109,NaN,4.59,20.0,0
997,998,03/13/2021,Betty,Stickels,bstickelsrp@cloudflare.com,Male,199.80.60.87,United States,7.54,20.0,0
998,999,03/17/2021,Paquito,Tesoe,ptesoerq@rakuten.co.jp,Male,0.183.63.11,United States,5.81,0.0,0
999,1000,03/23/2021,Rochelle,Pringuer,rpringuerrr@house.gov,NaN,170.193.249.83,Canada,8.01,20.0,0

In [11]:
del df['test']

In [12]:
df

,id,date,first_name,last_name,email,gender,ip_address,country,price_paid,tax
0,1,03/28/2021,Marylin,Alders,malders0@shop-pro.jp,Male,160.119.8.119,Canada,5.36,0.0
1,2,03/19/2021,Hinda,Harridge,hharridge1@gnu.org,Female,210.51.172.132,Canada,8.32,0.0
2,3,03/17/2021,Erl,Kilminster,ekilminster2@etsy.com,Male,213.8.101.145,United States,3.73,20.0
3,4,03/19/2021,Grata,Brantl,gbrantl3@umn.edu,Female,5.140.237.101,United States,3.70,20.0
4,5,03/24/2021,Kanya,Beasant,kbeasant4@jigsy.com,Male,106.252.162.233,Morocco,9.24,20.0
...,...,...,...,...,...,...,...,...,...,...
995,996,03/24/2021,Duff,Errigo,derrigorn@elpais.com,Female,193.84.247.144,France,3.63,0.0
996,997,03/17/2021,Ame,Rastall,arastallro@toplist.cz,Female,188.219.12.109,NaN,4.59,20.0
997,998,03/13/2021,Betty,Stickels,bstickelsrp@cloudflare.com,Male,199.80.60.87,United States,7.54,20.0
998,999,03/17/2021,Paquito,Tesoe,ptesoerq@rakuten.co.jp,Male,0.183.63.11,United States,5.81,0.0
999,1000,03/23/2021,Rochelle,Pringuer,rpringuerrr@house.gov,NaN,170.193.249.83,Canada,8.01,20.0

In [13]:
# df['price_total'] = df.price_paid - (df.price_paid * df.tax) / 100
df['price_total'] = df.price_paid * (1 - df.tax / 100)

In [14]:
df

,id,date,first_name,last_name,email,gender,ip_address,country,price_paid,tax,price_total
0,1,03/28/2021,Marylin,Alders,malders0@shop-pro.jp,Male,160.119.8.119,Canada,5.36,0.0,5.360
1,2,03/19/2021,Hinda,Harridge,hharridge1@gnu.org,Female,210.51.172.132,Canada,8.32,0.0,8.320
2,3,03/17/2021,Erl,Kilminster,ekilminster2@etsy.com,Male,213.8.101.145,United States,3.73,20.0,2.984
3,4,03/19/2021,Grata,Brantl,gbrantl3@umn.edu,Female,5.140.237.101,United States,3.70,20.0,2.960
4,5,03/24/2021,Kanya,Beasant,kbeasant4@jigsy.com,Male,106.252.162.233,Morocco,9.24,20.0,7.392
...,...,...,...,...,...,...,...,...,...,...,...
995,996,03/24/2021,Duff,Errigo,derrigorn@elpais.com,Female,193.84.247.144,France,3.63,0.0,3.630
996,997,03/17/2021,Ame,Rastall,arastallro@toplist.cz,Female,188.219.12.109,NaN,4.59,20.0,3.672
997,998,03/13/2021,Betty,Stickels,bstickelsrp@cloudflare.com,Male,199.80.60.87,United States,7.54,20.0,6.032
998,999,03/17/2021,Paquito,Tesoe,ptesoerq@rakuten.co.jp,Male,0.183.63.11,United States,5.81,0.0,5.810
999,1000,03/23/2021,Rochelle,Pringuer,rpringuerrr@house.gov,NaN,170.193.249.83,Canada,8.01,20.0,6.408

In [15]:
countries = {'United States': 'US', 'France': 'FR', 'Canada': 'CA', 'Morocco': 'MA'}
df['country_codd'] = df.country.map(countries)

In [16]:
df

,id,date,first_name,last_name,email,gender,ip_address,country,price_paid,tax,price_total,country_codd
0,1,03/28/2021,Marylin,Alders,malders0@shop-pro.jp,Male,160.119.8.119,Canada,5.36,0.0,5.360,CA
1,2,03/19/2021,Hinda,Harridge,hharridge1@gnu.org,Female,210.51.172.132,Canada,8.32,0.0,8.320,CA
2,3,03/17/2021,Erl,Kilminster,ekilminster2@etsy.com,Male,213.8.101.145,United States,3.73,20.0,2.984,US
3,4,03/19/2021,Grata,Brantl,gbrantl3@umn.edu,Female,5.140.237.101,United States,3.70,20.0,2.960,US
4,5,03/24/2021,Kanya,Beasant,kbeasant4@jigsy.com,Male,106.252.162.233,Morocco,9.24,20.0,7.392,MA
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,03/24/2021,Duff,Errigo,derrigorn@elpais.com,Female,193.84.247.144,France,3.63,0.0,3.630,FR
996,997,03/17/2021,Ame,Rastall,arastallro@toplist.cz,Female,188.219.12.109,NaN,4.59,20.0,3.672,NaN
997,998,03/13/2021,Betty,Stickels,bstickelsrp@cloudflare.com,Male,199.80.60.87,United States,7.54,20.0,6.032,US
998,999,03/17/2021,Paquito,Tesoe,ptesoerq@rakuten.co.jp,Male,0.183.63.11,United States,5.81,0.0,5.810,US
999,1000,03/23/2021,Rochelle,Pringuer,rpringuerrr@house.gov,NaN,170.193.249.83,Canada,8.01,20.0,6.408,CA